# -*- coding: utf-8 -*-
"""notebookaaedb99853

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/notebookaaedb99853-9725c9ea-bf72-48a5-b4bb-750b96c7fccb.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20241220/auto/storage/goog4_request%26X-Goog-Date%3D20241220T141647Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D0415b08d9ec13ec16b3870193cea2bdf214ffdf2b79d535d43de9b577c1268d1bde1458bead9519448f6a226a00d56dff66e153db4c4f7948b159352c0d289fd7dc2864632c1235a201b1b57b70db35ea24e20df1197c9f4bf4f38ccb23afe08675c26a180baa666d3b8f0390b4e719242cb416e299fd838fb54b157f50c053bb9070a5b5b2848d696b049eebba5ce38d58c7bd7ab3bfda7e5351cfbdd122a0de0e5216a466fdcc81cf6169e8dc3f610f18c309862123d747729c706f47fec394190827d384db42ced227f512b02220505cc3964d40609102278ff646a36babbe689164923d3716a1cfeb584584aba4337aefd98361b3391aa83bda2ac6527b8
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
rashminslnk_youtube_subscribers_data_2024_path = kagglehub.dataset_download('rashminslnk/youtube-subscribers-data-2024')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

